# mappings
unmap -
unmap >>
unmap <<
unmap m
unmap i
map t createTab
map q removeTab
map Q restoreTab
map h goBack
map l goForward
map d scrollPageDown
map D scrollPageUp
map u scrollPageUp
map U scrollPageDown
map j scrollFullPageDown
map k scrollFullPageUp
map w scrollToTop
map e scrollToBottom
map <a-c-h> previousTab
map H previousTab
map L nextTab
map <a-c-l> nextTab
map - visitPreviousTab
map J scrollDown
map K scrollUp
map <a-s-h> moveTabLeft
map <a-s-l> moveTabRight
map W moveTabToNewWindow
map <a-s-w> moveTabToNextWindow
map ] goNext
map [ goPrevious

# link hints
rewqfdsavcx
